<?php

/**
 * @file
 * Contains inshape_core.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
* Implements hook_theme to allow custom page.
*/
function return_forms_theme($existing, $type, $theme, $path) {

  return array(
    'product_return' => array(
      'render element' => 'form',
      'template' => 'product_return',
      'path' => $path . '/templates'

    ),
    'gift_certificate' => array(
      'render element' => 'form',
      'template' => 'gift_certificate',
      'path' => $path . '/templates'
    ),
  );
}