favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://vickiedean.dev/themes/custom/vickie_dean_themes/favicon.ico'
  use_default: true
schema: '8000'
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
cdn_jsdelivr_theme: bootstrap_theme
