favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://vickiedean.dev/themes/custom/vickie_dean_themes/favicon.ico'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  slideshow: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
