favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://vickiedean.dev/themes/custom/vickie_theme/favicon.ico'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
